version: "3.8"

services:
  api:
    build:
      context: ./backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    networks:
      - backend

  microsservico:
    build:
      context: ./services
    ports:
      - 8000:8000
    networks:
      - backend

networks:
  backend:
    driver: bridge
